"""empty message

Revision ID: 481fe8f00bce
Revises: f2c31b4abddc
Create Date: 2024-05-05 23:30:31.705077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481fe8f00bce'
down_revision = 'f2c31b4abddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('transaction_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_date', sa.DATE(), nullable=False))

    # ### end Alembic commands ###
